### ISSUE TITLE
Allow multiple TN-IDs for ESR file format

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.esr#12]
Currently, only one TN-ID can be set in the settings, which is then used for all generated files. In some cases, this doesn't work, as the system might be collecting for different IDs.

The solution is to add the TN-ID to the creditor ID, separated by a slash (``/``). If this is detected, it acts as an override on the TN-ID in the settings.

**Comment by bjendres** [comment]
will be released with ``1.6``

**Comment by abugey** [comment]
I think we can close here, right?
