### ISSUE TITLE
Additional export format

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.esr#13]
@abugey please add some details

**Comment by abugey** [comment]
The current export format doesn't work for printing QR Codes. The following new fields are needed in the new export format:
- QRType
- Version
- Coding Type
- Konto
- ZE Adresstyp
- ZE Name
- ZE Strasse
- ZE Haus-Nr.
- ZE PLZ
- ZE Ort
- ZE Land
- Währung
- EZP Adress-Typ
- EZP Name
- EZP Strasse/Adresse
- EZP Haus-Nr.
- EZP PLZ
- EZP Ort
- EZP Land
- Referenztyp
- Referenz
- ESR 1 Ref Zeile Grp
- PersNr
- Mailcode
- Adresszeile 1
- Adresszeile 2
- Adresszeile 3
- Adresszeile 4
- Adresszeile 5
- Titel
- Vorname
- Nachname
- Briefanrede
